### ISSUE TITLE
Nice work! 

### ISSUE THREAD

**Issue by lukebranch** [krocket/pincode-odoo#1]
This looks very promising for those of us that are looking for multi-factor authentication. Do you plan on adding some other features to this model for different types of multi-factor authentication?

I think this could integrate nicely with one of the SMS modules out there for authenticating accounts and phone numbers among other things (eg. facebook: forgotten password retrieval feature).

I know there are many people out there looking for these features to add an extra layer of security to logins.

**Comment by krocket** [comment]
Hi,

it is already possible, if you connect a mobile device to your server.
After, just add a  action to execute specific code...

**Comment by lukebranch** [comment]
@krocket ,

Thanks for the reply. I'll take a look at the module in more detail next week. It should come in handy for a number of different projects i'm working on.
